### PR TITLE
Add Appointment Functionality to Student and Teacher Interface

### PR DESCRIPTION
**Pull request by telecom2009**
As Cole requested in the last meeting, I pushed what code I had to my remote branch. However, when he requested I make a pull request this evening, I realized that my branch was already 25 commits behind master. Steven had warned us before that it gets complicated if you push before being up to date with master. At the time I pushed of course, everything was up to date. Rayan and I tried getting it up to date without any issues, but with no luck. I did not want to risk any problems for you guys, so I am making the pull request as-is and will wait for further instructions. Thanks.

### CODE REVIEW

**Comment by colegarien** [comment]
Don't worry Mossi, you can go ahead and push the rest of your commits (as long as you get the in before midnight). 

Me and Steven will worry about re-basing tomorrow morning

**Comment by telecom2009** [comment]
Honestly, I tried to push the rest of my commits, so I get very weird
situation that I end up to make another branch called ma_appointment_fixed,
so when I went to GitHub for pull request I saw the branch said"by
symbyte". Actuality it is first time to be in this situation
Thanks

Mossi

**Comment by colegarien** [comment]
It says symbyte because your 'fixed' branch has zero new commits compared
to master

**Comment by colegarien** [comment]
Also, if you had just pushed the rest of your commits to this branch, ma_appointment, then me or Steven could have re-based this

**Comment by telecom2009** [comment]
I understand now, all my commits had pushed on ma_appointment branch.
Thanks for explaining 

Mossi

**Pull request closed without merging**
