### PR TITLE
Fixed Piechart Labeling Size and Appearance Issues

### PR DESCRIPTION
**Pull request by telecom2009**
-Created absences table
-Corrected labeling size on piechart
-Corrected layout of piechart
-Corrected legend size on piechart

### CODE REVIEW

**Comment by symbyte** [comment]
On trying to open the student attendance section the app immediatly crashes with the following exception:

No virtual method getContext()Landroid/content/Context; in class Ledu/uco/schambers/classmate/Fragments/StudentAttendance; or its super classes (declaration of 'edu.uco.schambers.classmate.Fragments.StudentAttendance' appears in /data/app/edu.uco.schambers.classmate-2/base.apk)

A fragment does not have access to getContext(). You should use getActivity instead.

**Comment by colegarien** [comment]
I believe Rayan jad a similar issue with his branch, I think that get does
work of you run AndroidM

**Comment by symbyte** [comment]
Oh, I see. He must be testing on an emulator that is running M. In this case its a good idea to run the emulator on apis 22 and 18 to make sure that your changes are going to work on our devices as well. I wonder why the added that in android M, seems weird because the activity is perfectly capeable of acting as a context as it inherits from context ¯_(ツ)_/¯

**Comment by symbyte** [comment]
Rebasing, fixing crash and retesting.

**Comment by symbyte** [comment]
No more crashes, though there are some low priority issues I would like to see addressed in the next sprint. Check the issue tracker for details!

Overall, nice work. Everything looks good. Merging in.

**Pull request merged**
