### PR TITLE
Added Scrollable Table With Test Values Populated by Listener

### PR DESCRIPTION
**Pull request by ralhamami**
-Added table row for table headers
-Added scollable layout to house table layout
-Added table layout to house table rows of student data
-Added Student class with properties: student name, absences, and course
-Added dummy values to use for testing
-Added onItemSelectListener for class selection Spinner
-Within onItemSelected, added code for dynamic table population

### CODE REVIEW

**Comment by ralhamami** [comment]
Hey Steven. Okay, I have watched your tutorial over and over, read all of the stuff on Google Groups again, and chatted with Cole to ensure I didn't screw anything up with VCS. I did run into a couple of problems, but I tried to follow everything as carefully and correctly as possible. If you see any problems at all, please advise me and I would be happy to fix them immediately. Thanks buddy.

**Comment by ralhamami** [comment]
Oh, and I ensured that it compiled and ran smoothly from my end to avoid any issues.

**Comment by symbyte** [comment]
Hey rayan. It looks like all of these commits are based on pull request number 20 from a few days ago. No worries, I'll see what I can do to fix it.

Always remember that merging is never something that should be done on your end, if android studio suggests a merge, it is best to back out of the operation you were performing and get help. I would be more than happy to provide guidance in these situations. 

Something about branches: you are not meant to keep the exact same branch all the way through development. Through the lifecycle of this project you will branch many times. In this instance, it looks like you kept working on the same branch that you submitted your last update on, which seems to be the source of some of your trouble. What should have been done would have been much simpler for you: 

1)Branch off of the latest version of master with a branch name like ra_add_table_and_values. 
2)make your commits to that branch
3)push that branch to github and file your pull request, no merging or rebasing needed. 

Let me be clear I don't blame you at all for making this mistake, I have made it many times. VCS in general is not a transparent process at all, and it requires a big picture understanding of the whole system to be able to grasp even the simplest details. 

It is for this reason that in the very near future I will be holding a mini git workshop either at my house or over hangouts that anyone in the team is welcome to attend. I'll be going over all of the big concepts in a visual way that, I hope, makes them easier to get ahold of. 

That said, I'll do everything I can to make the needed corrections to the branch here, but I'm not going to merge until after today to prevent people from perhaps downloading a newer version of the app than everyone has (which Dr. Sung would penalize us for in our demos). Thanks for getting the contributions in so early, it means a lot.

**Comment by symbyte** [comment]
Ok, so here's what I have done: I created a new branch to house your commit based off of the very latest version of master, and I did what is called a cherry-pick. Now, I want to thank you for giving me a scenario where I could learn this command, because I have never been in a situation that calls for it. I'm not being sarcastic, I have been dieing to learn how to use cherry-pick, but the situations where it actually can be used are very rare. 

Cherry picking does sort of what it sounds like. It will take one commit from any other branch and apply it to whatever branch you are on, You notice that there were a ton of extra commits included in your pull request because of the merges, right? I was able to just go and take the one that contains your feature, and copy it to its own branch that is based off of the very newest version of master, eliminating the need for any merging.

Im going to create a new pull request based off of that new branch so you compare it with this one and sort of see what I mean by what I did. We'll use that pull request to merge when the time comes, so I'm going to close this one.

**Pull request closed without merging**
