### PR TITLE
Integrated achartengine Library for Pie-Chart Display of Attendance

### PR DESCRIPTION
**Pull request by telecom2009**
-Added AttendanceRecord class for test records (class name, attendances, absences)
-Converted all data to hardcoded ArrayList of AttendanceRecord objects
-Imported achartengine libraries in order to implement pie chart rendering
-Configured properties and rendering within a draw method in order to be displayed upon selection of a class

### CODE REVIEW

**Comment by symbyte** [comment]
Application crashes immediatly when I press the button for student attendance.

**Comment by ralhamami** [comment]
Hmm. Odd. We both tested it, but there obviously must be something we missed. I'll get in touch with him ASAP and see if we can get it turned around.

**Comment by symbyte** [comment]
Also from what I can tell you are still using the 1.7 JDK instead of 1.8. Its not a big problem but you are going to want to update that as soon as you can to make sure you are using the same JDK as the rest of us.

**Comment by symbyte** [comment]
I'm trying to find the root cause of the crash now, I'll let you know if I find it.

**Comment by ralhamami** [comment]
Sounds great. Thanks. Oh, and I'll let him know about the JDK version as well if I'm in touch with him first.

**Comment by symbyte** [comment]
Found an initial cause for the crash. It looks like you guys were trying to get the context that the array adapter needs from the fragment instead of calling getActivity(). Will test to see if this resolves the crash and push the fix if it works.

**Comment by symbyte** [comment]
That fixed the first crash, but now there is a crash after the fragment opens. Investigating.

**Comment by symbyte** [comment]
That crash was caused by a similar issue, I am pushing my fixes so that you guys can see what I did.

**Comment by symbyte** [comment]
Testing, everything is running clean now. 

Achartengine is a pretty cool little library. Good find. A note though (I will create an issue for this in the issue tracker) I can see that there is text pointing to each part of the chart, but no matter how much I zoom in on the chart itself, the text never gets bigger and is impossible to read. Chart itself looks good though, nice work.

I rebased the branch and am merging it in now. Please check the issue tracker for an issue assigned to you about correcting the small text.

**Comment by ralhamami** [comment]
Glad it worked out. :+1:

**Pull request merged**
