### PR TITLE
Nelson cloud authenticat user

### PR DESCRIPTION
**Pull request by nelalison**
Cloud sign_up and sign_in
wrapper for user_Info done 
Passwords for signin #44 -> fixed

### CODE REVIEW

**Comment by symbyte** [comment]
Nelson,

In the future make sure your banch is up to date with the very newest version of master before you push your branch and create a pull request. When you pushed your branch it was behind master, but I am rebasing it myself.

Also, dont close issues yourself unless you were the one that created the issue. The person that creates the issue is the one that decides whether or not your code actually fixes the issue. Just reference the issue number in your commit (just like you did) and we will check and see if your commit fixes said issue. 

Testing now, will merge in if good.

**Comment by symbyte** [comment]
Problems so far:
1. When logging in with a user that I created in the cloud, if I enter the wrong password the app just crashes.
2. When I sign up, the screen just sits there for a while (probably because it is connection to the web server to create the user) but no indication is given as to what is going on, so it feels like the app is just lagging or something. It would be good to have some sort of indicator to let the user know that signing up is taking place.

**Comment by symbyte** [comment]
When you fix these changes, your going to need to delete the local version of this branch since I had to rebase it, and then checkout the origin version "as a new local branch" like I showed you before. Get in contact with me if you need help and ill get back with you as soon as I can

**Comment by nelalison** [comment]
steven and cole
Error fixed when signing in with the cloud....you can test and merge

**Comment by symbyte** [comment]
Testing now.

Good job on the branch management, btw. Everything looks perfect with the git branches.

**Comment by symbyte** [comment]
everything tests clean, and this fixes #53 and the second point of #44 (still need to adjust the password length, shouldn't be a problem). Closing issue #53 and leaving #44 open. 

merging in, nice work.

**Pull request merged**
