### PR TITLE
Added Note Functionality for Individual Student Attendance Records

### PR DESCRIPTION
**Pull request by ralhamami**
-Updated onBackPressed in MainActivity to pop the backstack in TeacherAttendanceItem instance
-Added Descriptive Comment to onBackPressed
-Wasn't recalling values correclty
-Now storing values with tag of student's name prefixed with "attNote"
-Changed approach to AlertBuilder Dialog, and instead of adding views directly to dialog, I created a layout oject, added the edittext view with a hint to the layout, as well as a datepicker
-I also extracted the date into a string to make the code more readable
-Tested and working so far before and after restarts

### CODE REVIEW

**Comment by symbyte** [comment]
Sorry its has taken me so long to get to this, its been a crazy morning.

Remember that getContext() calls only work on api 23 and above, so it is better to use getActivity() instead to ensure that devices running lower than api 23 are able to run the program. I'm pushing a commit that makes this change. Android stutio should be letting you know that getContext() cant be used at our API level, but it sometimes takes a while for it to show those inspections (sometimes its taken days to notify me). I'm going to push a commit to fix this and retest.

**Comment by symbyte** [comment]
something else i notice that the table allignment is a bit off (sort of like with the other tables that you made a few weeks ago). We don't have much time to investigate this, and its not a huge deal for now. I will just merge this in for now and we will fix it in sprint 6.

**Comment by symbyte** [comment]
screenshot_2015-11-10-12-25-27

a screenshot of the alignment issue for your information

**Comment by ralhamami** [comment]
Oh darn. I knew I wanted to come back and change that getContext () call and forgot. Thanks bud. I appreciate you taking care of it. 

I'll see what I can do about that table alignment in the coming fixes.

Anyhow, hope you liked the updates. Thanks. :+1:

**Pull request merged**
