### PR TITLE
Mm db demo

### PR DESCRIPTION
**Pull request by liveyourheart**

### CODE REVIEW

**Comment by colegarien** [comment]
It seems this branch needs to be re-based

**Comment by colegarien** [comment]
Does this branch do the same as the fix-thomas-button branch?

**Comment by liveyourheart** [comment]
this is finally somewhat finished.  it does include the thomas button fix, but i believe he also committed something.  There may be some conflicts, but I can sort those out if need be.  I should have had everybody send me their Fragment names earlier.

this commit -
added userInformation Fragment, Updated the sign up page to better reflect what nelson had worked on, it now includes the database and shared preferences.  The validation is still pretty messy, but I imagine I can leave that for next week.

**Comment by symbyte** [comment]
If i click the sign up button without keying in anything the app crashes. The poblem seems to be with the student ID text box, because when press sign up with the student check box unchecked, it does not crash.

**Comment by symbyte** [comment]
Also, keep the discussion about these pull requests IN the pull requests. The whole point of a pull request is for there to be a conversation about the code, and it is very difficult to tell what was said when you only have one part of the conversation.

**Comment by nelalison** [comment]
Steven, I think it is crashing because there is no validation step up. If
Matt wants I could help him create some kind of validation for all the
input?

**Comment by symbyte** [comment]
No, his commits claim that there is ( "messy") validation in place. The code is throwing a parse int exception.

**Comment by liveyourheart** [comment]
I can fix the validation later today.

Matt McHughes

**Comment by liveyourheart** [comment]
validation for empty edit texts is fixed.  I also had to change a few lines in DataRepo that were causing me crashes last night.  Also, I need to validate the db unique ids which was causing me a crash last night, but not sure if that is not something that can't be fixed later.

**Comment by symbyte** [comment]
Ok, the crash no longer happens as it did before. But the sql table definition is still throwing an exception, most likely because you cant define an id column to be not null. As a consequence, the id is not stored in the database. If I change this sql back, though, I get a toast saying passwords dont match, but it still signs me in. And then if i click the user info button it crashes. @colegarien I am very hesitant to merge this into the project in its current state, would you mind having a look?

**Comment by nelalison** [comment]
I could look at and fix it if I can pull it.

**Comment by symbyte** [comment]
You would do this by running the git fetch command, and the purple origin version of this branch will show up in your git log, then you open the branch menu and do checkout as new local branch on the origin/mm_db_demo branch

from there you can make commits and then use the push command to push those commits

**Comment by symbyte** [comment]
If I leave the student ID field blank and press sign up the app crashes. Seems to still be failing when trying to parse an integer from an empty string.

**Comment by symbyte** [comment]
the previously mentioned crash is fixed, but now after signing in the app crashes when you press the user info button.

**Comment by symbyte** [comment]
please test the application fully when submitting the next fix.

**Comment by colegarien** [comment]
This branch also needs to be rebased

**Pull request closed without merging**
