### PR TITLE
Nelson sdd adapter

### PR DESCRIPTION
**Pull request by nelalison**
UserInfo bug Fixed

### CODE REVIEW

**Comment by colegarien** [comment]
It looks like Matt has a copy of this branch he is working on

**Comment by nelalison** [comment]
I dont understand what is going on. You emailed me yesterday and asked me
to fix the user info and submit a pull request, which I did. You still did
not merge it

**Comment by colegarien** [comment]
Steven, I have tested it and it seems fine. I just want another set of eyes to make sure everything is good. (may need a re-base before merging?)

**Comment by symbyte** [comment]
So some issues I have run into with the login screen:
- I guess the decision was made to limit passwords to be only 4 characters long? From what I understand you guys wanted to include a password to add security, but imposing such a counter intuitive restriction works against that in a pretty big way. This wouldn't have been a big deal to me if it wern't for:
- When I entered a password that did not satisfy these requirements, I was only told what was wrong with my password on my 7 or 8th attempt to log in, all the other times it would just pop up the exclaimation mark, but not tell me the problem with the password, so there is come inconsistancy with when this warning comes up that needs to be addressed. 

Aside from this, I like how the sign up interface has been simplified. I like the use of placeholder text instead of seperate lables. Makes everything much cleaner. One little thing I would probably change for the email input though is to use the email input type for the EditText (I think this was actually being used before, but now its not) to give easy access for email specific characters on the keyboard (the @ and .com etc.)

**Comment by colegarien** [comment]
Yeah, the password warning only really shows text if you are on that box when you press login,

Now I think the issues mentioned are going to be addressed by Matt after merge?
If we do merge we should put the issues in the tracker. We can talk with Matt about it during the meeting though just to check.

**Comment by symbyte** [comment]
That sounds fine to me, to make the process easy Ill just push my rebased local version of their branch and merge it in and add this issue to the tracker, that way we dont have to worry about this branch falling behind master again.

**Pull request merged**
