### PR TITLE
Wz new checkin display

### PR DESCRIPTION
**Pull request by wenxi-zeng**
Changes, 
- Add a list view in the student fragment to accept multiple services. 
- Move the functionality from check in button to the list view.
- The services with same class name, professor name and ip address will only be recognized once.

To test it,
- Long press a list view item to check in.
- For multiple services, use at least three phones. Two of them go to TeachRollCall to start a service. the other one goes to StudentRollCall. The started services should be added to the list view of StudentRollCall. 

For the bugs you mentioned, I have found the reason of the infinity check-in problem. I’ll fix it on my next commit along with starting the service of StudentQestionService.

### CODE REVIEW

**Comment by symbyte** [comment]
Works perfectly, thanks Wenxi!

One thing I would suggest, though, is perhaps making the list view a little bit bigger. When I was testing at first the size of the list view window made it appear as though there was only one class detected, but I saw when I finally figured out that I needed to scroll that there were indeed 2 classes listed. 

No hurry on this, you can just include it in your changes for next sprint if you want. But if you wanted to quickly push a commit today that makes this change that would be fine with me too (it would probably be really easy. I'll leave this open until you let me know how you want to do it.

**Comment by wenxi-zeng** [comment]
Ah. Right. I should mention it needs to be scrolled down to view more services. But the interface is intended to be designed like this, so it looks neat. I'll probably add a hint on the status label when I get home. I'll let you know when this branch is ready to be merged. :)

Sent from my Windows Phone

**Comment by symbyte** [comment]
Ok Wenxi, sounds great. I'll test and merge it as soon as you push your 
commit.

**Comment by wenxi-zeng** [comment]
Alright Steven. This branch is ready for merging. Thanks a lot!

**Comment by symbyte** [comment]
Tested and looks good. Merging now.

**Pull request merged**
