### PR TITLE
this is stuedent attendance

### PR DESCRIPTION
**Pull request by telecom2009**

### CODE REVIEW

**Comment by symbyte** [comment]
There is no reason for you to change the min sdk version. Why did you do it?

**Comment by colegarien** [comment]
This branch is 45 commits behind I believe, I think that is why the SDK min version is off

Mossi, rebase

**Comment by symbyte** [comment]
As far as I am aware there is not a single pull request merged in that changed the min sdk away from 18. This is a change he had to have made himself, I would think.

**Comment by telecom2009** [comment]
I so sorry, I did not mean do it, I believe after I cloned the project, I just to add my files, then I committed the project I unselect any files that I didn't work in it.

**Comment by symbyte** [comment]
Mossi, unless you rebase your branch and change the min sdk version back, we will not be able to merge your code.

**Comment by telecom2009** [comment]
Did rebase my branch and i change the min sdk to 18, but I got error message while I rebase it "cannot rebase: You have upstaged change."
what I did (I went to VCS -> Git -> rebase, then I select my branch to rebase)
Is that correct?!

**Comment by symbyte** [comment]
when you made the change back to sdk 18, that gave you an unstaged change. you need to commit that change to your branch then rebase. cole has excellent instructions on the google group on how to rebase

**Comment by telecom2009** [comment]
I just did commit change then I did rebase, so Is my branch change right now?

**Comment by symbyte** [comment]
Nothing will change on github until you push your branch.

**Comment by symbyte** [comment]
this has not been rebased correctly. It is still 40 or so commits behind master.

**Comment by symbyte** [comment]
It also seems like you rebased this onto a past version of master that still had the project name bug

**Comment by symbyte** [comment]
Something I noticed when trying to fix this. your fragment tries to make a call to this.getContext(). There is absolutely no way that this code ran on your local system, because class Fragment does not have the method getContext(), it dosn't even compile. I can understand making a mistake, but this makes me feel like this code wasnt even run before you pushed it to the github, which is very poor form indeed.

**Comment by symbyte** [comment]
Somehow I was able to rebase everything onto master without having to keep some of the commits that broke the project. Branch has been force pushed to overrite previous unrebased version of branch. Merging.

**Pull request merged**
