### PR TITLE
fixed backstack bug following logout

### PR DESCRIPTION
**Pull request by liveyourheart**
Fixes: #120 

+cleaned up additions to backstack to all be to null
+cleared backstack after logout.

### CODE REVIEW

**Comment by colegarien** [comment]
The only problem I found is the following
1. Logout
2. Log back in
3. The back button must be hit at-least twice to exit the app

**Comment by nelalison** [comment]
Just a thought......I was thinking normally that's how must apps work. What
could be done, is to toast a message saying "press back twice to exit"
after the first press.

**Comment by liveyourheart** [comment]
fixed this with a commit by not adding user information fragment to the
backstack.

**Comment by colegarien** [comment]
This works great, but I have one question before I merge this;
For the Sign Up and the 'send email link', shouldn't it go back to the Sign In page instead of closing the app?

**Comment by liveyourheart** [comment]
If you want to merge, I'll get those in a separate pr.

Matt McHughes

**Comment by liveyourheart** [comment]
I'm not sure if this is the pr that you meant to merge.  This one should be
fine other than converting it to an asynctask.  Instead of merging the
other one, I'll just update another commit fairly quickly and let you know
when it's done.

**Comment by liveyourheart** [comment]
oops disregard that last email.  I had my issues mixed up.

**Pull request merged**
