### PR TITLE
Spinner class selection box added

### PR DESCRIPTION
**Pull request by ralhamami**

### CODE REVIEW

**Comment by symbyte** [comment]
It was said during the meeting (that you missed, unfortunatley) and in the google group (that perhaps did not get read) that we can't use the debug fragment for our end of sprint demo, so if I took this code as is it would not actually integrate into the project.

I will give you a freebie because your branch is actually up to date with master (which is exactly how everyone should do it), and I will push a commit that wires it in.

I need to know before I merge this code into the project. What is your fragment supposed to do? I see a dropdown box, but when I select it it does nothing.

This is the reason that it asks you to submit a description. This description is supposed to tell us what your code is supposed to do, so we don't have to ask you. This information will always be needed so always include it. We need this information to verify that your code actually does what you say it does. Please dont make us guess what your code does, it makes it harder for us to accept it and bring it into the code base.

**Comment by symbyte** [comment]
Also note above: the nice thing about pull requests is that it allows for the adding of commits. I was able to add this commit just by pushing to your remote branch (which is what you did to get your branch to show up so you could do a pull request). Just pointing out this handy feature because not many people seem to know this can be done yet.

**Comment by symbyte** [comment]
Rayan, if you do not respond to the question asked here I will not be able to merge your code.

**Comment by ralhamami** [comment]
Okay, all sounds good. Sorry things have been hectic this semester. What the spinner/dropdown box is supposed to do is allow the instructor to select the class, which will then be followed by the display of a sortable table that contains a list of the students in that class (first name, last name) and the number of absences. The reason nothing happens yet is because I am still trying to work out the best way to do this. I do not want to simply add something for the sake of showing you all work. I would actually like to make the group as happy with my module as possible. So, for just this sprint, the dropdown box is just that, a dropdown box. It has no function yet, as I am still trying to work out the details. I would be happy to add a thing or two if you would like though. Hope that clarifies. I'll make sure these are done correctly on the next round. Thanks

**Comment by symbyte** [comment]
No problem, Rayan. We just always need to know what your intent with the code is so that we can tell if it is behaving correctly or not. Thanks for getting back with me. I'll start merging your part in now.

**Comment by ralhamami** [comment]
Sounds good Steven. Thanks for taking the time to comment.

**Pull request merged**
