### PR TITLE
Rework display question results

### PR DESCRIPTION
**Pull request by herpderp25**
Now reads data from an arraylist of IQuestions
All views are now programatically added so that it works with questions with more/less than 4 choices

### CODE REVIEW

**Comment by symbyte** [comment]
I am confused by the addition of the TestQuestion2 class you added. Ideally your fragment should be prepared to receive a list of IQuestion objects directly, not a list of some class that implements the IQuestion interface.

As a practical example consider the IQuestion interface itself. It has every method you would need to see what answer was selected by whoever answered the question. So to see what the responses were, you would simply iterate over a list of IQuestion objects 

```
List<IQuestion> questions; //some questions you receieve in on fragment start

List<String> collectedAnswers = new ArrayList<>();
for( IQuestion q : questions)
{
    String answer = q.getAnswer();
    collectedAnswers.add(answer);
}
```

then you can run whatever analysis on the answers that you want, instead of creating a whole new type of question object that we will never actually send you and thus making the code that you've written with respect to this TestQuestion unusable. 

Since youre not yet getting data from our fragments (but you will very soon) you could extend IQuestion like you did with TestIQuestion.java, but don't add any new methods, because you wolnt be able to refer to them (because your fragment should be expecting to receive objects that have the IQuestion reference type). 

So your mock data creation could look like this:

```
//create mock data

IQuestion mockQuestion = new TestIQuestion();
mockQuestion.answerQuestion(mockQuestion.getQuestionChoices.get(0)); //set the question response to the first item in the list of choices
```

This makes sure that you are only using methods made available by the IQuestion interface which will keep you from going back and rewriting your code when you start working with real data.

**Comment by symbyte** [comment]
Is the sole purpose of TestIQuestion2 to have 5 choices instead of 4? Unless I'm missing something it looks like that is the case. If so, it would be better to use descriptive naming for the classes that you write when extending IQuestion. Something like WoodChuckQuestionFourChoices, while long, would be totally suitable here becase it tells those of us who didnt write it exactly what it is, which helps a lot. Then you could have had the variant WoodChuckQuestionFiveChoices and we would know exactly why there needs to be two variants on this class, instead of having to guess with the sequel like naming scheme.

Long discriptive class names are good, especially given that android studio does much of our typing for us anyway.

**Comment by symbyte** [comment]
Also, when I run the app, it still only displays the 4 choice variant of the wood chuck question, so there is not any evidence that your fragment _can_ display a question based on how many choices it has. If you address this and the naming concern (this one is easy, just right click the class source file and use the context menu to go to refactor > rename. this will also rename all of your uses of the class in the program) I will retest and merge if everything tests clean. 

The longer it takes for this to get done the less likely it is that it will be brought into the project for this sprint. I can't speak for Cole, but I'm going to have a very busy next couple of days.

**Comment by herpderp25** [comment]
Ok, i have a list of IQuestions and i populate it using the answerQuestion() method call. 
I renamed the testing class to IQuestionWoodchuck5 choices and it no longer has any additional methods added. It should all work with just a List of IQuestions as input now. 
I have ran it multiple times with 3,5, and 6 choice questions and they all display properly for me. let me know if it still only shows 4 choices for you.

**Comment by symbyte** [comment]
Thanks for doing all of that.

I think I'm missing something, how do I get it to display something other than the 5 response question now? I only see one button and no way to configure the question in the application while its running.

**Comment by symbyte** [comment]
Are you just changing the choices in your custom IQuestion object and recompiling and running?

**Comment by herpderp25** [comment]
I was having issues with everything being in the on create method so i
moved it all to a button (ill be fixing that very soon. I was just getting
silly errors i couldnt figure out right away). The button just acts like a
page load. When i get home i can change it real quick to have buttons for
different numbers of choices to show that it works properly with different
inputs if you want. Let me knkw

**Comment by herpderp25** [comment]
Yes, that is how i have it set up now.

**Comment by symbyte** [comment]
Oh ok, I just wanted to make sure I understood what you are doing. If you are going to demo that your results display is now dynamic, it would be a good idea to have a way to display the different numbers of responses at runtime.

**Comment by symbyte** [comment]
All of the changes so far look much better, though. Thank you.

**Comment by symbyte** [comment]
Looks good, rebasing and merging now.

**Comment by symbyte** [comment]
Also, make sure to not duplicate commit messages. You can avoid this by clicking the "ammend commit" button if you want to add more changes to a given commit. See PR #82  for more about this.

**Pull request merged**
