### PR TITLE
Wz checkin enhancement

### PR DESCRIPTION
**Pull request by wenxi-zeng**
Changes:
- Fixed the problem of checking-in indefinitely
- Add search button for refreshing discover service
- Disconnect from a class when teacher stops it
- Send teacher the student PK id instead of student id
- Start student question service once checked-in successfully

Note:
- All of the testing devices have to have a WiFi connection. Otherwise the discoverService gives an error code of "busy".
- Another situation may causes the indefinite checking-in: On student side, kill the app while it has a connection with teacher side. Then re-launch the app, try to check-in again. The problem appears. This is because the P2P connection is not terminated, the port is busy, so it refuse to establish the connection again. I'll fix it by next week.

### CODE REVIEW

**Comment by wenxi-zeng** [comment]
@symbyte Steven, can you help me test it on your Sumsung devices? See if the check-in problem solved. Also, please check if I correctly start the student question service. Thanks

**Comment by symbyte** [comment]
From what I can tell based on your commits you started my service exactly right. I'll test everything with all my devices if not tomorrow then Saturday afternoon.

**Comment by wenxi-zeng** [comment]
OK. No rush. Take your time. :)

Sent from my Windows Phone

**Comment by symbyte** [comment]
When a student checks into a course now the PK of the student is displayed instead of the student ID (this is expected because of the change you mention in the pull request). @colegarien will probably have to slighly change his implementation to get the student ID to display once more.

**Comment by symbyte** [comment]
Wenxi, Unfortunately the samsung phone is not able to discover the teacher service. I'm also noticing that now every time that a student tries to connect to the teacher service the teacher is having to accept the invitation to connect every time it is connected, which was not the case before. Can you investigate this? 

I performed a rebase on your branch, so make sure you delete your local version and fetch the new remote to push more changes.

**Comment by wenxi-zeng** [comment]
The service cannot be found even if the search button is clicked? That's strange. I'll need to borrow my friend's Sumsung phone to further investigate the problem. About the invitation, it is expected, since the device deletes the remembered group information every time. It ensures the device not to remember itself as group owner. Otherwise, the indefinite checking-in problem will occur.

Sent from my Windows Phone

**Comment by symbyte** [comment]
There is no search button that I can see. Where should it be?

**Comment by wenxi-zeng** [comment]
Thank you for doing the rebase. It's really a pain for me. I'll probably look into the problem tonight, or tomorrow.

Sent from my Windows Phone

**Comment by wenxi-zeng** [comment]
The search button suppose be on the right up corner, the action bar. It's a menu item.

**Comment by symbyte** [comment]
Ok, I thought thats where it should be. It was not there when I looked 
when testing.

**Comment by wenxi-zeng** [comment]
That's weird. I'll check it when I got my friend's phone.

Sent from my Windows Phone

**Comment by colegarien** [comment]
Been about 4 days since last commits, Closed for now

**Pull request closed without merging**
