### PR TITLE
Wz checkin enhancement

### PR DESCRIPTION
**Pull request by wenxi-zeng**
Changes:
- Fixed the problem of checking-in indefinitely
- Add search button for refreshing discover service
- Disconnect from a class when teacher stops it
- Send teacher the student PK id instead of student id
- Start student question service once checked-in successfully

Note:
- All of the testing devices have to have a WiFi connection. Otherwise the discoverService gives an error code of "busy".
- Another situation may causes the indefinite checking-in: On student side, kill the app while it has a connection with teacher side. Then re-launch the app, try to check-in again. The problem appears. This is because the P2P connection is not terminated, the port is busy, so it refuse to establish the connection again. I'll fix it by next week.

### CODE REVIEW

**Comment by wenxi-zeng** [comment]
@symbyte Steven, please try one more time. See if the refresh button appears on the action bar.

**Comment by symbyte** [comment]
the refresh button is there now, but it does not allow the samsung phone to find the class when pressed

**Comment by symbyte** [comment]
I think that something you did changed the way the connections happen, previously after updating my samsung phone to android 5.0 i believe the connections were working fine. Now it asks for the teacher to accpet the connection invitation every time the connection is made, where that didnt happen before, so maybe that change is part of the problem.

**Comment by wenxi-zeng** [comment]
OK. I'm fixing it now.

**Comment by wenxi-zeng** [comment]
Ah. Your suggestion reminds me one thing. After added the remove group information method, same situation happened in my devices once. The devices couldn't find each other even on WiFi settings. Then I did reboots for both devices. Afterwards, everything works as usual. 
Can you do me one more favor? Go to settings->wifi->wifi direct, and see if the devices can find each other on there. If not, reboot the devices, see if it works by then.

**Comment by symbyte** [comment]
After rebooting they are able to see each other in wifi direct, but the 
samsung phone still can not find the class session, even after reboot.

**Comment by wenxi-zeng** [comment]
= =|| The device differences drive me crazy. In the Samsung phone I borrowed it works fine. I can only fix the problem by guessing now. I'll try to improve the remove group information method, see if it can address the problem. 
Thanks a lot for testing it for me.

**Comment by symbyte** [comment]
yeah its really frustrating =/

Let me know when there's anything else you want me to test. Thanks for 
working so hard on this.

**Comment by wenxi-zeng** [comment]
Steven, I made some changes. Now the app should only ask for accepting invitation at the first time. Could you have another look. Hopefully, the service discovery issues is addressed at the same time. = =||

**Comment by symbyte** [comment]
Okay, the invitation now only happens on the first attempt to connect. The samsung phone is still not able to see the teacher session, though.

**Comment by symbyte** [comment]
Also after trying to reconnect a third time the nexus phone is not able to find the session either. The applcation on the student side said "Internal error, try restarting the application". After restarting it on both phones the session from the teacher can not be discovered by the student, regardless of phone type.

**Comment by wenxi-zeng** [comment]
OK. Steven. One more time. The last time. I'm pretty sure this time would work. :)

**Comment by symbyte** [comment]
That fixed the previous problem. Samsung still cant see the class though =(

**Comment by wenxi-zeng** [comment]
Oh. No. I totally have no idea now. Can you merge this branch first? I'll visit back for this problem if we still have time.

**Comment by symbyte** [comment]
Sure, No problem. Thanks for trying tonight, though!

**Comment by wenxi-zeng** [comment]
Ha. Thank you for helping me test all the time.

**Pull request merged**
