### PR TITLE
Added Sorting Functionality/Additional Improvements

### PR DESCRIPTION
**Pull request by ralhamami**
-Added onItemSelectedListener for "Sort" Spinner control
-Added method buildTable() to dynamically build the table
-Modified onItemSelectedListener for Course selection Spinner to call the method buildTable for building the rows dynamically, as opposed to doing it locally
-Added sort methods for sorting by student's name or student's number of absences that each take a String argument to indicate whether ascending or descending is desired
-Added swap method as an accessory to sorting methods
-Added conditional statements to onItemSelectedListener for "Sort" Spinner to call each sorting function accordingly, followed by a call to buildTable() to rebuild the table rows
-Added Last name to Student test class, as well as all necessary modifications to support it
-Added Last name to group of dynamically allocated rows as well as a new column header
-Removed "All" as an option for course selection based on Steven's insightful recommendation
-Cleaned up some unused code and imports in various positions
-Removed Labels for Spinners, and instead added "Labels" to the Spinner items themselves
-Modified sortByName to sort by last name instead of first name
-Made some various adjustments to the layout properties

### CODE REVIEW

**Comment by ralhamami** [comment]
Hey Steven, it looks like there is an old commit there. I ran into a bit of an issue with the R file, and I managed to mess everything up. I know I already have had some updates since last sprint, but I really wanted to get this sorting thing in for the next demo, so I worked throughout the night on cleaning things up. Thankfully, I recovered from the issues. Hope it's all good on your end.

**Comment by symbyte** [comment]
Ignore the above reference, I was just demonstrating how to use the issue tracker in the issue I created for Mossi.

**Comment by symbyte** [comment]
testing this now, will rebase and merge if everything tests clean

**Comment by symbyte** [comment]
(by the way, you adding this branch scared the holy hell out of me (lol) cause you added it right when I was doing a rebase on someone elses branch to merge it in. I thought I completely destroyed the repo but was relieved to see it was just your banch showing up =P)

**Comment by symbyte** [comment]
Everything looks good, merging.

**Comment by symbyte** [comment]
@colegarien as a note to cole, for some reason when I merged the branch on github it did not totally merge all of the commits for a reason that I could not find. In order to get the commits in, I had to merge locally and push directly to master.

**Comment by ralhamami** [comment]
Hahaha, geez. I'm glad it was a false alarm. We believe in you man. You got this, haha. Well, I'm glad everything looks clean. Thanks a lot for your time.

**Pull request merged**
