### PR TITLE
Teacher Roll Call UI

### PR DESCRIPTION
**Pull request by colegarien**
**Additions**
- 'Cole' buttton now Links to TeacherRollCall Fragment
- TeacherRollCall Fragment has essentially UI elements
  - Teacher EditView for testing teacher name input
  - Class EditView for testing class name input
  - Start Roll Call Button (currently makes Toast)
  - ListView for listing connected students

### CODE REVIEW

**Comment by symbyte** [comment]
Did you manually change away from using the gradle wrapper or was that automatically done by your android studio settings? From what I understand using the wrapper is generally recommended, but I don't know if it makes a difference (at least I dont think so). 

Fetching the branch and testing now.

**Comment by colegarien** [comment]
Anything that is not the Java or XML files was done by Android Studio

**Comment by symbyte** [comment]
Ok, I figured so. Its not breaking anything so I'm not going to worry about it.

**Comment by symbyte** [comment]
As for the interface, Ideally wouldnt the teacher always be the same person? It seems odd to me that we would ask them to type their name every time they call roll when, if we need that information, we could just grab it from the registration they put when they set up the application the first time. I know that we don't have this running yet, but we could use some sort of placeholder to represent this. 

It might also be better from a UX standpoint if they were able to select what class they are calling roll for from a list view, given that the classes they will be managing will be consistent from week to week in a semester and what classes they have will eventually be stored in the database for the purposes of viewing the attendance of those classes.

**Comment by colegarien** [comment]
These are great Ideas and I planned on working this out once we had the simple registration implemented.

Currently EditText views are used because this registration process is not complete, once the teacher name is saved somewhere that is where the name will be gathered from (I will then probably switch the EditViews to TextView just to display the teacher name)

**Comment by symbyte** [comment]
Sounds good to me.

**Pull request merged**
