### PR TITLE
Final Bug Fixes and Cleanup, As Well As Piechart Fix

### PR DESCRIPTION
**Pull request by ralhamami**
See commits for details

### CODE REVIEW

**Comment by ralhamami** [comment]
Oh, forgot to mention, I took the sorting functionality out completely. It's a shame. I really thought it was a neat feature, but there just wasn't enough time to get it up and running again since integrating the DB with my module.

**Comment by symbyte** [comment]
Rayan, For some reason the piechart graphic itsself now no longer appears. Please investigate this and report your findings. 

Also, I rebased your branch, so make sure you pull the remote version of your branch so you are working with the rebased copy.

**Comment by ralhamami** [comment]
I've investigated it as quickly as possible. It looks like as long as both values are not 0, as they are in this case, then the pie chart will actually appear. I may be wrong here, but could you possibly confirm that? I'll see if I can do roll call for one class and test it and get back to you. I will be sure to pull the remote branch.

Hope you've had a good Thanksgiving buddy.

**Comment by symbyte** [comment]
Ok, that's what the problem was. I can confirm that it works as you 
describe. Thanks for having a look, and happy holidays.

**Comment by ralhamami** [comment]
That's wonderful news. My pleasure. Happ holidays to you as well buddy! :+1:

**Pull request merged**
