### PR TITLE
Sc question response notification

### PR DESCRIPTION
**Pull request by symbyte**
In this update:

-A broadcast reciever was added that is responsible for creating notifications that, when clicked will launch the StudentResponseFragment.

-For testing, the "send" button in the StudentResponseFragment will send out the broadcast that creates the notification.

-for @Perrofrijole , a static factory method is included in new broadcast reciever that will allow him easy access to an intent that, when broadcast, will be caught by the broadcast reciever.

-the MainActivity was given a function that can be used to implement launching any given fragment if the activity was started with an intent containing an action. It defaults to launching the debug fragment otherwise, currently.

### CODE REVIEW

**Comment by symbyte** [comment]
The only reason that is showing up as a change is because I refactored the name of my fragment. The main activity has implemented my communication interface since the beginning in the event that I decide to use it

**Comment by symbyte** [comment]
I think I may have found the source of the problem. I added the classmate.iml file back into version control, try with the newest commit and let me know

**Comment by colegarien** [comment]
Just testing, on your page when the Send button is pressed to send an answer, a notification pops up about receiving a question then click this opens the page to send an answer.

Is this how this should function?

**Comment by symbyte** [comment]
For now, yes. It was the easiest way I could test that he notification works. The indended behavior is for connors module to make a call to the broadcast reciever, so I left the test code in there for now to demonstrate how the call would be made.

**Pull request merged**
