### PR TITLE
Interactive Attendance Table

### PR DESCRIPTION
**Pull request by ralhamami**
-Added "Sort" textview header
-Added "Sort" Spinner with no functionality as of yet
-Removed "Course" column from student list as it is already assumed
-Added "All" option to "Class Selection" Spinner
-Added "All" condition to conditional statement on lines 170 and 171 of this update
-Added borders to both "Class Selection" and "Sort" Spinner
-Modified and cleaned up the general layout

### CODE REVIEW

**Comment by ralhamami** [comment]
Okay Steven, here it is. I followed your pointers as close as I possibly could, along with your comments on my previous pull requests. I tested beforehand and everything is running great. How does it look on your end? I hope it meets the standards. Thanks buddy.

**Comment by ralhamami** [comment]
I did just realize, however, that I forget the author block. I will make those changes for my next push though.

**Comment by colegarien** [comment]
I think you may know this, I don't know if we talked about it, You can still add commits to this branch even while the Pull Request is open.

**Comment by ralhamami** [comment]
Oh, awesome. Thanks for that bit of info. I'll go ahead and push the new ones over then. Okay done. Took care of it. Thanks Cole!

**Comment by symbyte** [comment]
Everything tests clean, merging in. Nice work. 

I wonder though: since an "all" option is introduced, dosn't that give at least a little need for the course column? I think that it is much cleaner without the column, your instinct is good there. I guess I'm having trouble seeing a situation when a teacher would need to see their attendance across all classes...I'm not a teacher though, so I don't know, I suppose

**Comment by ralhamami** [comment]
Hey, thanks. I'm glad everything looked clean. Also, thanks for your input. You know, I think you're right. I'll take it out for now, and we'll see towards the end if you all feel like I should put it back in or not. Thanks again man.

**Pull request merged**
