### PR TITLE
Master

### PR DESCRIPTION
**Pull request by Perrofrijole**
Merging master into CArcher to update my repository with the latest changes.

### CODE REVIEW

**Comment by Perrofrijole** [comment]
I'm confused, I need permission to merge from the master into my own repository? Or did I do something wrong?

**Comment by symbyte** [comment]
Something went very wrong here. You may not have rebased your branch correctly before pushing your commits to the remote. I can't really get a good look at things because my internet is down and the github android app isn't super detailed. Also it's not recommended that anyone merge their own pull requests because it gives others a chance to review code and test it before merging it to master. For now either Cole or I have been handling pull requests so you should just assign them to one of us for the sake of convenience. At any rate I'll have a look at things when my internet returns and see if I can get things sorted. @colegarien is welcome to it though as well, as I have no idea when my internet will be back.

**Comment by colegarien** [comment]
This isn't right, it looks like you merged master into your branch instead of rebasing.

From what I can see CArcher is simply Master with a 'Merge' commit that didn't do anything, i.e. CArcher seems that same as Master.

For future reference do not interact with master. As Steven mentioned, just submit a pull request and we will handle it.

**Comment by liveyourheart** [comment]
I apologize. I will review what I did wrong, I thought I was only working in my branch.  I will review what I did and create whatever fixes are necessary.

Matt McHughes

**Comment by symbyte** [comment]
I don't see that you did anything wrong, Matt. Do you see anything he might have done Cole? Still don't have internet so I'm bound to the Android app. It looks like Connor tried to merge master into his branch instead of reading his branch to the latest commit on master.

**Comment by colegarien** [comment]
Yeah, it doesn't look like master was effected. Connor just merged master into his own branch instead of rebasing

**Comment by liveyourheart** [comment]
Sorry, I thought this was a response to one of my commits.

**Comment by symbyte** [comment]
It's cool, man you're doing fine!

**Pull request merged**
