### PR TITLE
UI for student roll call

### PR DESCRIPTION
**Pull request by wenxi-zeng**
Initial UI for student to check-in classes. Student can change their preference, mute or vibrate when checked-in class, on the menu at the right corner of the screen. The menu item is added programmatically, so that it wouldn't affect the menu in other modules.

### CODE REVIEW

**Comment by colegarien** [comment]
Wenxi this looks good but can you add a description instead of "No description provided."

It is good to get into the habit now for when your branches contain more complex updates

**Comment by colegarien** [comment]
Wenxi, there is one thing you should fix before I merge:

**When Check in button is pressed it shifts over to the left when the text changes**

Once this is fixed I will merge

**Comment by wenxi-zeng** [comment]
Cole, I've fixed the bug that you mention. Thanks draw that in my attention. I've added the description as well.

**Comment by symbyte** [comment]
I can also verify the bug is fixed now. I'll go ahead and merge it in.

**Pull request merged**
