### PR TITLE
Adding style

### PR DESCRIPTION
**Pull request by liveyourheart**
Phase 1 of styling
+added overall theme with UCO in mind
+added animation and created prototype logo for sign in screen
+added error blinking animation for all set errors

### CODE REVIEW

**Comment by symbyte** [comment]
Github literally will not allow me to merge this branch because it is behind master and contains conflicts with master. I'll try to do a rebase, but without having been the one to write the code it will be hard for me to determine what should be merged perfectly. We'll see how it comes out.

**Comment by symbyte** [comment]
A few things on the style additions:

In material design it is generally not recommended to use colored backgrounds and reserve the use of color for things of importance like buttons, the toolbar etc. Using the a non off-white backround causes the background to have more emphasis than the components on the screen, which can be confusing to the eye.

Instead of making all of the changes you did, you could achieve the same sort of effect and still theme the app to be in UCO colors by following the instructions here:

http://developer.android.com/training/material/theme.html

These changes are simple but can have a dramatic effect. Changing the button colors to be in line with the color pallate you choose to use with material would also have a nice unifying effect. 

You can select from some precompiled color pallates here (you could probably just select the one that closest matches the uco blue):

https://www.google.com/design/spec/style/color.html#

**Comment by symbyte** [comment]
It would be my recommendation to, since this branch is behind and conflicting with master, to start off with a new branch based on master to implement the simple additions suggested above.

**Comment by liveyourheart** [comment]
gotchya.  I know you're pressed for late submissions, so I'll probably just
redo it and miss the deadline.  I apologize for that.

-Matt

**Comment by symbyte** [comment]
Thats perfectly fine. I'm willing to make concessions for those that 
submitted something for the deadline last night and I request them to 
make additional changes.

**Pull request closed without merging**
