### PR TITLE
Corrected Formatting in Class Management Table and Corrected Redundan…

### PR DESCRIPTION
**Pull request by ralhamami**
…t Classes

-Defined custom (generic) layouts for table views as they were being added which hopefully corrects the alignment issue
-Defined table layout reference outside of the classItem loop, and remove all views once class is selected in order to repopulate the table without redundancy

### CODE REVIEW

**Comment by ralhamami** [comment]
Okay Steven. I think I corrected the formatting. I had to test it on the Nexus 5 emulator running 23, and everything checked out. I can't guarantee the same from your device, but fingers crossed it will check out there too. Let me know how it goes. Thanks for the heads up by the way. :+1:

**Comment by symbyte** [comment]
The formatting is closer to correct on the nexus 5, but its still a ways off on the nexus 6. I can't imagine it will be much better on other devices. I think the root of the problem is that your headder rows are not actually inside the table where you're adding the data rows. Is there a particular reason you have chosen to do this in this way?

**Comment by symbyte** [comment]
looking at it, your fix should still be giving better results than the ones I'm seeing, I'm going to tinker with it for a moment if you dont mind

**Comment by symbyte** [comment]
I was able to make the tablelayout work for all devices. Check out my commit if you are curious about my fix. 

Merging.

**Comment by symbyte** [comment]
Edit: only half of my fix got committed for some reason when I pushed to your branch, I had to merge the other half of my changes in this request, check it out if you are curious 

#103

**Comment by ralhamami** [comment]
Okay fantastic. Yeah, I think that was just a mistake. I actually meant to put the header inside the table layout I believe. Thanks. I'll check it out now.

**Pull request merged**
