### PR TITLE
Nelson class management

### PR DESCRIPTION
**Pull request by nelalison**
- persist new classes created to cloud
- get and render list to class management UI

### CODE REVIEW

**Comment by colegarien** [comment]
Why are there two commits that are exactly the same?

**Comment by nelalison** [comment]
The previous commit does not have all the files i made changes to, so I had
to do another commit.

**Comment by colegarien** [comment]
Ok, next time you should check the 'amend commit' box so that there are not
two commits with the same text

**Comment by ralhamami** [comment]
Hey Cole, I believe I had a commit in there that was identical in description as the other one. My apologies for that. I had made some additional changes and hadn't double checked before committing again. I'll be sure to avoid that in the future.

**Pull request merged**
