### PR TITLE
Added Selectable Table Rows with Student Attendance Data Pie Chart Fragment

### PR DESCRIPTION
**Pull request by ralhamami**
-Added onItemTouchListener to dynamically created rows
-onTouch action DOWN, darkened background color temporarily to indicate action
-onTouch action DOWN, created new fragment object, push current fragment to backstack, attach attendance data, and replace current fragment with new fragment
-Added TeacherAttendanceItem fragment that is closely based on Mosa's StudentAttendance fragment, with some code removals and modifications
-Added fragment_teacher_attendance_item.xml layout which is also closely based on StudentAttendance module, but without the course selection spinner
-Attendance data is pulled from fragment arguments
-Added author block to TeacherAttendanceItem.java
-Added author block to fragment_teacher_attendance_item.xml
-Updated Author block to TeacherAttendance.java

Left out in Previous Commit:
-Removed junk code and unused imports
-Added more explanatory comments
-Tidied up the look of the code

### CODE REVIEW

**Comment by symbyte** [comment]
I'm going to be busy all day today and out of town for a wedding tomorrow, so Cole should probably handle this one I'm thinking

**Comment by colegarien** [comment]
Yeaj  i will take a look after class

**Comment by colegarien** [comment]
Testing Now

**Comment by ralhamami** [comment]
Sounds good Steven. Good luck with everything!

Thanks for taking a look at it Cole.

**Comment by colegarien** [comment]
It seems that this only works on phones that are running Android M,

the culprit is TeacherAttendanceItem.java line 106 -> @TargetApi(Build.VERSION_CODES.M)
You have to add an alternative method if the use is not running android M, tested this on an API18 phone and it results in a crash when pressing a student element

**Comment by colegarien** [comment]
I am going to close this PR until the issue is looked at, 
you may want to use an emulator and set it to API level 18

**Pull request closed without merging**
