### PR TITLE
Auto login

### PR DESCRIPTION
**Pull request by liveyourheart**
+updated to work with API 18 by taking out unhandled null string

### CODE REVIEW

**Comment by liveyourheart** [comment]
updated to work with api 18

**Comment by colegarien** [comment]
Instantly crash upon opening the app, from what I can tell it looks like the code does not consider the case inwhich the token is an empty string... see error from android below

Caused by: java.lang.NullPointerException
            at edu.uco.schambers.classmate.Database.TokenUtility.parseUserToken(TokenUtility.java:11)
            at edu.uco.schambers.classmate.Fragments.Auth.initUI(Auth.java:141)
            at edu.uco.schambers.classmate.Fragments.Auth.onCreateView(Auth.java:100)
            at android.app.Fragment.performCreateView(Fragment.java:1699)

**Comment by liveyourheart** [comment]
this fix should allow users who currently have an auth_token that is empty to see a login screen and prevent the app from crashing.  My last fix didn't take into account users who already had an auth_token, but the auth_token was empty.

**Comment by symbyte** [comment]
I just rebased this to be in line with the latest version of master. Tested and everything works as described. There are is a low priority issue with these changes, but I will merge them in now and the issue can be addressed at a later time. Look for the issue in the issue tracker after I merge.

**Pull request merged**
