### PR TITLE
Added CSV Import for Schools in Class Management and Made UI Improvements

### PR DESCRIPTION
**Pull request by ralhamami**
-Changed ui to include table similar to teacher_attendance module
-Added csv file to raw resources directory with up to date school name stats
-Added Scanner to read from csv
-Scanner is read from, and lines from csv are split (delimited by commas)
-Spinner for schools is updated based on state spinner selection
-School names are full length. Small algorithm implemented to trim into abbreviation before adding to table
-Testing still as there may be areas that could use improvement for the next sprint

### CODE REVIEW

**Comment by symbyte** [comment]
Your code does not compile. on line 121 of your class management fragment you make a reference to R.raw, but the raw directory does not exist in resourses. Any idea what could be happening here? Did you maybe forget to include the raw directory in your commit?

**Comment by ralhamami** [comment]
Perhaps I did. Sorry about that. Let me check it out and see if I can fix it real quick buddy.

**Comment by ralhamami** [comment]
Okay, I believe I took care of it. The directory should be there now. I also swapped some function arguments in the ClassAdapter because they were flipped around, causing the School Name and Class Name to be switched.

**Comment by symbyte** [comment]
Ok, so at first the fragment would crash right when I would press the button to launch it, but I was able to push a commit to fix that. See commit I pushed if you are interested.

Also, your table formatting is off: the data in the table is not aligning with the table headers. I am going to merge this branch into master now in order to commit the merge conflicts I had to resolve when rebasing this branch. If you want to fix this before the demo, create a separate pull request based on the latest master and do it quickly.

Thanks for your contributions. The CSV use was clever.

**Comment by ralhamami** [comment]
Okay, I'll try to get those fixes in as quickly as possible. It's my pleasure. I'm glad I can contribute to the team's success, and glad you liked the CSV implementation. :+1: Thanks a lot for your hard work as well. I know you're doing this alone today, so it is greatly appreciated man.

**Comment by ralhamami** [comment]
Quick question. Since I am trying to recreate the environment you caught the formatting errors in, could you share you emulator specs with me?

**Comment by symbyte** [comment]
no emulator, nexus 5 and nexus 6 both running 5.1.1

**Comment by ralhamami** [comment]
Fantastic. Thanks. I'll check it out and get it in as soon as possible.

**Pull request merged**
