### PR TITLE
Mm add login

### PR DESCRIPTION
**Pull request by liveyourheart**
+login screen now in debug awaiting validateUser functionality
+added logout functionality in menu
+updated user information page
+added reset password page
+added reset password on user information page, but awaiting validateUser functionality

### CODE REVIEW

**Comment by colegarien** [comment]
Just testing and noticed two things:
- 'Student ID:' has a colon but none of the other fields do
- logged in as a student, logged out, logged in with new credentials but the User Info page still shows the original login credentials.

**Comment by colegarien** [comment]
Two more things:
- 'Current Password', 'New Password', etc have colons, this is inconsistent with the sign in page
- Change password functionality on User Info Page does not appear to work, is this intended to be implemented later?

**Comment by liveyourheart** [comment]
I was looking through the logs and it seems as if password is never saved correctly. Adding another log in user information as I have for getName and getEmail crashes the application saying that there is no message present.  I believe this might be the cause of all of our problems, but i haven't figured out what's causing it.

**Comment by liveyourheart** [comment]
fixed password bug, allows logging in to work properly.  Changing password still does not work as expected.  Will talk to Nelson about proper update of database.

**Comment by symbyte** [comment]
I see a merge with master above. Again, never merge anything, at all. Especially not with master.

**Comment by symbyte** [comment]
Something that I have noticed in testing:
- If I create a user and then completely exit the application, I am not given an obvious way to log in again as the user I created and am forced to sign up again

I'm going to try to merge this branch while github still says there are no conflicts. I need to say this though: this branch is entirely too large. There are easily 4-5 different distinct features housed in this one branch, where we should be aiming for one branch for feature. This creates two problems: 
1. you are forcing yourself to work a feature before the previous one is fully finished, which makes it hard to keep track of the work that you need to get done. You should only work on one feature at a time for the sake of your sanity, juggling all of this stuff at once is simply not easy.
2. you are trying to have one branch represent all of these features, which leads to the branch getting extremely large, and in this case very tangled as well. Trying to fit everything in one branch leads to the branch being active for a long time, which has the unfortunate side effect of requiring more maintenence (like how you have had to merge often to keep up). This is avoided entirey by limiting yourself to one feature per branch. Making several pull requests, one for each finished feature. This makes it easier on everyone involved, especially on you. 

That said, before this branch gets any further out of control, I'm going to merge it in. I will then create issues in the issue tracker for each outstanding change that will need to be made this next sprint, each of which should be addressed with its own pull request (and therefore its own branch).

**Comment by symbyte** [comment]
::Gulp:: 
Here goes the merge. Wish me luck.

**Pull request merged**
